### ISSUE TITLE
修改mailer组件from-address硬编码

### ISSUE THREAD

**Issue by teebbstudios** [teebbstudios/TeebbCoreBundle#2]
修改mailer组件from-address硬编码，应解析MAILER_DSN中的地址

**Comment by teebbstudios** [comment]
已修改为在teebb_core.yaml配置文件中手动配置发送地址和地址名称。

```yaml

    #邮件发送人配置此项必须配置，请修改为您的配置
    from_email:
        address: sender@quanweiwei.cn
        address_name: TEEBB.COM管理员

```
